--Script de criação
--criando a tabela para cadastrar uma tarefa
CREATE TABLE TAREFA(
IDTAREFA UNIQUEIDENTIFIER NOT NULL,
NOME NVARCHAR(150)		  NOT NULL,
DESCRICAO NVARCHAR(250)   NOT NULL,
DATA		DATE		  NOT NULL,
HORA TIME				  NOT NULL,
PRIORIDADE NVARCHAR(10)	  NOT NULL,
PRIMARY KEY(IDTAREFA)

)
GO

--ALTERAR
ALTER TABLE TAREFA ADD CONSTRAINT CHECK_PRIORIDADE
CHECK(PRIORIDADE IN ('BAIXA', 'MEDIA', 'ALTA'))
GO